---
# Installing a single Xcode version (no longer?) takes a long time (~60min)
- name: Ensure selected Xcode versions are installed
  block:
    - name: Enable passwordless sudo
      lineinfile:
        path: /etc/sudoers
        line: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
      become: yes
    - shell: $SHELL -lc 'xcodes update' # ensure available Xcodes list is updated
    - shell: $SHELL -lc 'xcodes install {{ item|quote }} --empty-trash {{ extra_install_flags | join(' ') }}' # when using shell always use quote filter to avoid injection
      args:
        creates: '{{ xcode_root }}/Xcode-{{ item }}.app'
      async: 3600 # accounts for download + install
      poll: 60
      loop: "{{ xcodes }}"
  always:
    - name: Disable passwordless sudo
      lineinfile:
        path: /etc/sudoers
        line: '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'
        state: absent
      become: yes

- name: Ensure .zprofile exists
  ansible.builtin.file:
    path: ~/.zprofile
    state: touch
    mode: '0644'
    modification_time: preserve
    access_time: preserve

- name: 'Ensure Xcode {{ default_xcode }} is added to .zprofile'
  ansible.builtin.lineinfile:
    path: ~/.zprofile
    regexp: '^export DEVELOPER_DIR='
    line: 'export DEVELOPER_DIR={{ xcode_root }}/Xcode-{{ default_xcode }}.app'
