---
- name: Ensure aria2 and xcodes are installed
  community.general.homebrew:
    name:
      - aria2 # Will speed up Xcode and Runtime download immensely... or so they say
      - xcodesorg/made/xcodes
    state: present

- name: Check if using Oh My Zsh
  stat:
    path: ~/.oh-my-zsh
  register: omz
  check_mode: false

- name: Ensure Oh My Zsh completions path exists
  file:
    path: ~/.oh-my-zsh/completions
    state: directory
  when: omz.stat.exists

- name: Ensure xcodes completions are updated
  shell: $SHELL -lc 'xcodes --generate-completion-script > ~/.oh-my-zsh/completions/_xcodes'
  when: omz.stat.exists
